"""Database connection handling and schema for every GridShift table, on SQLite locally or Postgres when hosted."""

import re
import sqlite3
from contextlib import contextmanager
from datetime import datetime, timezone
from pathlib import Path

import psycopg

SCHEMA = """
CREATE TABLE IF NOT EXISTS runs (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    created_at TEXT NOT NULL,
    horizon_start TEXT NOT NULL,
    status TEXT NOT NULL,
    payload TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS weather_cache (
    kind TEXT PRIMARY KEY,
    fetched_at TEXT NOT NULL,
    payload TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS users (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    email TEXT NOT NULL UNIQUE COLLATE NOCASE,
    name TEXT,
    role TEXT NOT NULL,
    status TEXT NOT NULL,
    password_hash TEXT NOT NULL,
    created_at TEXT NOT NULL,
    last_login_at TEXT
);
CREATE TABLE IF NOT EXISTS sessions (
    token_hash TEXT PRIMARY KEY,
    user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    created_at TEXT NOT NULL,
    expires_at TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS auth_tokens (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    kind TEXT NOT NULL,
    token_hash TEXT NOT NULL UNIQUE,
    expires_at TEXT NOT NULL,
    used_at TEXT,
    created_by INTEGER,
    created_at TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS audit_log (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    at TEXT NOT NULL,
    user_id INTEGER,
    user_email TEXT,
    action TEXT NOT NULL,
    outcome TEXT NOT NULL DEFAULT 'success',
    entity TEXT,
    entity_id TEXT,
    summary TEXT,
    detail TEXT,
    ip TEXT,
    user_agent TEXT
);
CREATE INDEX IF NOT EXISTS audit_at ON audit_log(at);
CREATE INDEX IF NOT EXISTS audit_user ON audit_log(user_id);
CREATE INDEX IF NOT EXISTS audit_action ON audit_log(action);
CREATE TABLE IF NOT EXISTS app_settings (
    key TEXT PRIMARY KEY,
    value TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS data_files (
    dataset TEXT NOT NULL,
    name TEXT NOT NULL,
    content TEXT NOT NULL,
    PRIMARY KEY (dataset, name)
);
"""

PG_SCHEMA = (
    SCHEMA.replace("INTEGER PRIMARY KEY AUTOINCREMENT", "BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY")
    .replace("INTEGER", "BIGINT")
    .replace(" COLLATE NOCASE", "")
)

Target = Path | str


def is_postgres(target: Target) -> bool:
    """Return whether a database location is a Postgres URL rather than a SQLite file."""
    return isinstance(target, str) and target.startswith(("postgres://", "postgresql://"))


class Row(dict):
    """Result row readable by column name or position, like sqlite3.Row."""

    def __getitem__(self, key):
        if isinstance(key, int):
            return list(self.values())[key]
        return super().__getitem__(key)


def _row_factory(cursor):
    names = [c.name for c in cursor.description or []]
    return lambda values: Row(zip(names, values))


def _pg_sql(sql: str) -> str:
    return re.sub(r"\bLIKE\b", "ILIKE", sql.replace("%", "%%").replace("?", "%s"))


class PgConnection:
    """Postgres connection offering the sqlite3 calls GridShift uses, with SQLite's case-insensitive LIKE."""

    def __init__(self, conn: psycopg.Connection):
        self.conn = conn

    def execute(self, sql: str, params: tuple | list = ()):
        """Run one statement written with ? placeholders and return its cursor."""
        cursor = self.conn.cursor(row_factory=_row_factory)
        cursor.execute(_pg_sql(sql), tuple(params))
        return cursor


def _pg_connect(url: str) -> psycopg.Connection:
    return psycopg.connect(url, prepare_threshold=None)


def _migrate(db: sqlite3.Connection) -> None:
    """Add columns introduced after a database was created."""
    columns = {r[1] for r in db.execute("PRAGMA table_info(runs)")}
    if "dataset" not in columns:
        # Runs from before data sets existed belong to neither the sample nor the live data.
        db.execute("ALTER TABLE runs ADD COLUMN dataset TEXT NOT NULL DEFAULT 'legacy'")


def now_iso() -> str:
    """Return the current UTC time as ISO text."""
    return datetime.now(timezone.utc).isoformat(timespec="seconds")


def iso(moment: datetime) -> str:
    """Return a datetime as UTC ISO text."""
    return moment.astimezone(timezone.utc).isoformat(timespec="seconds")


def init_db(path: Target) -> None:
    """Create the database and every table."""
    if is_postgres(path):
        with _pg_connect(path) as conn:
            conn.execute("SELECT pg_advisory_xact_lock(3405)")
            conn.execute(PG_SCHEMA)
            conn.execute("ALTER TABLE runs ADD COLUMN IF NOT EXISTS dataset TEXT NOT NULL DEFAULT 'legacy'")
        return
    path.parent.mkdir(parents=True, exist_ok=True)
    db = sqlite3.connect(path, timeout=30)
    try:
        db.execute("PRAGMA journal_mode = WAL")
        db.executescript(SCHEMA)
        _migrate(db)
    finally:
        db.close()


@contextmanager
def connect(path: Target):
    """Yield a connection that commits on success and rolls back on error."""
    if is_postgres(path):
        conn = _pg_connect(path)
        try:
            yield PgConnection(conn)
            conn.commit()
        except BaseException as exc:
            conn.commit() if getattr(exc, "keeps_writes", False) else conn.rollback()
            raise
        finally:
            conn.close()
        return
    db = sqlite3.connect(path, timeout=30, isolation_level=None, check_same_thread=False)
    db.row_factory = sqlite3.Row
    db.execute("PRAGMA foreign_keys = ON")
    db.execute("PRAGMA journal_mode = WAL")
    db.execute("BEGIN")
    try:
        yield db
        db.execute("COMMIT")
    except BaseException as exc:
        db.execute("COMMIT" if getattr(exc, "keeps_writes", False) else "ROLLBACK")
        raise
    finally:
        db.close()


def one(db: sqlite3.Connection, sql: str, params: tuple = ()) -> dict | None:
    """Return the first row as a dict, or None."""
    row = db.execute(sql, params).fetchone()
    return dict(row) if row else None


def rows(db: sqlite3.Connection, sql: str, params: tuple | list = ()) -> list[dict]:
    """Return every row as a dict."""
    return [dict(r) for r in db.execute(sql, params).fetchall()]


def insert(db: sqlite3.Connection, table: str, values: dict) -> int:
    """Insert a row and return its id."""
    columns = ", ".join(values)
    marks = ", ".join("?" for _ in values)
    return db.execute(f"INSERT INTO {table} ({columns}) VALUES ({marks}) RETURNING id", tuple(values.values())).fetchall()[0][0]
